# ~/.config/alacritty/alacritty.toml

[colors.primary]
background = '0x282828' # Gruvbox dark background
foreground = '0xebdbb2' # Gruvbox light foreground

[colors.normal]
black = '0x282828'
red = '0xcc241d'
green = '0x98971a'
yellow = '0xd79921'
blue = '0x458588'
magenta = '0xb16286'
cyan = '0x689d6a'
white = '0xa89984'

[colors.bright]
black = '0x928374'
red = '0xfb4934'
green = '0xb8bb26'
yellow = '0xfabd2f'
blue = '0x83a598'
magenta = '0xd3869b'
cyan = '0x8ec07c'
white = '0xebdbb2'

[window]
opacity = 0.7 # Adjust this value for desired transparency
